### ISSUE TITLE
Test failures on s390x (GCC 10.2.1 and 11.0.1)

### ISSUE THREAD

**Issue by sanjayankur31** [gsl-lite/gsl-lite#304] opened 2021-04-19 09:06 UTC
Hello,

While building gsl-lite for inclusion in Fedora, we're seeing tests fail on s390x:

```
+ /usr/bin/ctest --output-on-failure --force-new-ctest-process -j3
Test project /builddir/build/BUILD/gsl-lite-0.38.0/s390x-redhat-linux-gnu
      Start  1: gsl-lite-v0-cpp98.t
      Start  2: gsl-lite-v0-cpp11.t
      Start  3: gsl-lite-v0-cpp14.t
 1/12 Test  #1: gsl-lite-v0-cpp98.t ..............***Failed    0.01 sec
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1694: failed: byte_span(): Allows to build a span of gsl::byte from a single object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1704: failed: byte_span(): Allows to build a span of const gsl::byte from a single const object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/issue.t.cpp:72: failed: byte: aliasing rules lead to undefined behaviour when using enum class [issue #34](GSL issue #313, PR #390): 14 == F::f( i, reinterpret_cast<gsl::byte&>( i ) ) for 14 == 7
3 out of 343 selected tests failed.
      Start  4: gsl-lite-v0-cpp17.t
 2/12 Test  #2: gsl-lite-v0-cpp11.t ..............***Failed    0.01 sec
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1694: failed: byte_span(): Allows to build a span of gsl::byte from a single object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1704: failed: byte_span(): Allows to build a span of const gsl::byte from a single const object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/issue.t.cpp:72: failed: byte: aliasing rules lead to undefined behaviour when using enum class [issue #34](GSL issue #313, PR #390): 14 == F::f( i, reinterpret_cast<gsl::byte&>( i ) ) for 14 == 7
3 out of 419 selected tests failed.
      Start  5: gsl-lite-v0-cpp20.t
 3/12 Test  #3: gsl-lite-v0-cpp14.t ..............***Failed    0.01 sec
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1694: failed: byte_span(): Allows to build a span of gsl::byte from a single object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1704: failed: byte_span(): Allows to build a span of const gsl::byte from a single const object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/issue.t.cpp:72: failed: byte: aliasing rules lead to undefined behaviour when using enum class [issue #34](GSL issue #313, PR #390): 14 == F::f( i, reinterpret_cast<gsl::byte&>( i ) ) for 14 == 7
3 out of 419 selected tests failed.
      Start  6: gsl-lite-v1-cpp98.t
 4/12 Test  #4: gsl-lite-v0-cpp17.t ..............***Failed    0.00 sec
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1694: failed: byte_span(): Allows to build a span of gsl::byte from a single object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1704: failed: byte_span(): Allows to build a span of const gsl::byte from a single const object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/issue.t.cpp:72: failed: byte: aliasing rules lead to undefined behaviour when using enum class [issue #34](GSL issue #313, PR #390): 14 == F::f( i, reinterpret_cast<gsl::byte&>( i ) ) for 14 == 7
3 out of 419 selected tests failed.
      Start  7: gsl-lite-v1-cpp11.t
 5/12 Test  #6: gsl-lite-v1-cpp98.t ..............***Failed    0.00 sec
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1694: failed: byte_span(): Allows to build a span of gsl::byte from a single object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1704: failed: byte_span(): Allows to build a span of const gsl::byte from a single const object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/issue.t.cpp:72: failed: byte: aliasing rules lead to undefined behaviour when using enum class [issue #34](GSL issue #313, PR #390): 14 == F::f( i, reinterpret_cast<gsl::byte&>( i ) ) for 14 == 7
3 out of 329 selected tests failed.
      Start  8: gsl-lite-v1-cpp14.t
 6/12 Test  #5: gsl-lite-v0-cpp20.t ..............***Failed    0.01 sec
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1694: failed: byte_span(): Allows to build a span of gsl::byte from a single object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1704: failed: byte_span(): Allows to build a span of const gsl::byte from a single const object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/issue.t.cpp:72: failed: byte: aliasing rules lead to undefined behaviour when using enum class [issue #34](GSL issue #313, PR #390): 14 == F::f( i, reinterpret_cast<gsl::byte&>( i ) ) for 14 == 7
3 out of 419 selected tests failed.
      Start  9: gsl-lite-v1-cpp17.t
 7/12 Test  #7: gsl-lite-v1-cpp11.t ..............***Failed    0.01 sec
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1694: failed: byte_span(): Allows to build a span of gsl::byte from a single object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1704: failed: byte_span(): Allows to build a span of const gsl::byte from a single const object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/issue.t.cpp:72: failed: byte: aliasing rules lead to undefined behaviour when using enum class [issue #34](GSL issue #313, PR #390): 14 == F::f( i, reinterpret_cast<gsl::byte&>( i ) ) for 14 == 7
3 out of 405 selected tests failed.
      Start 10: gsl-lite-v1-cpp20.t
 8/12 Test  #8: gsl-lite-v1-cpp14.t ..............***Failed    0.01 sec
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1694: failed: byte_span(): Allows to build a span of gsl::byte from a single object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1704: failed: byte_span(): Allows to build a span of const gsl::byte from a single const object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/issue.t.cpp:72: failed: byte: aliasing rules lead to undefined behaviour when using enum class [issue #34](GSL issue #313, PR #390): 14 == F::f( i, reinterpret_cast<gsl::byte&>( i ) ) for 14 == 7
3 out of 405 selected tests failed.
      Start 11: gsl-lite-v1-special-cpp98.t
 9/12 Test #11: gsl-lite-v1-special-cpp98.t ......   Passed    0.00 sec
      Start 12: gsl-lite-v1-special-cpp11.t
10/12 Test #10: gsl-lite-v1-cpp20.t ..............***Failed    0.01 sec
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1694: failed: byte_span(): Allows to build a span of gsl::byte from a single object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1704: failed: byte_span(): Allows to build a span of const gsl::byte from a single const object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/issue.t.cpp:72: failed: byte: aliasing rules lead to undefined behaviour when using enum class [issue #34](GSL issue #313, PR #390): 14 == F::f( i, reinterpret_cast<gsl::byte&>( i ) ) for 14 == 7
3 out of 405 selected tests failed.
11/12 Test  #9: gsl-lite-v1-cpp17.t ..............***Failed    0.01 sec
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1694: failed: byte_span(): Allows to build a span of gsl::byte from a single object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/span.t.cpp:1704: failed: byte_span(): Allows to build a span of const gsl::byte from a single const object: spn[0] == to_byte( 0xff ) for 0x7f == 0xff
/builddir/build/BUILD/gsl-lite-0.38.0/test/issue.t.cpp:72: failed: byte: aliasing rules lead to undefined behaviour when using enum class [issue #34](GSL issue #313, PR #390): 14 == F::f( i, reinterpret_cast<gsl::byte&>( i ) ) for 14 == 7
3 out of 405 selected tests failed.
12/12 Test #12: gsl-lite-v1-special-cpp11.t ......   Passed    0.00 sec
17% tests passed, 10 tests failed out of 12
Total Test time (real) =   0.03 sec
The following tests FAILED:
	  1 - gsl-lite-v0-cpp98.t (Failed)
	  2 - gsl-lite-v0-cpp11.t (Failed)
	  3 - gsl-lite-v0-cpp14.t (Failed)
	  4 - gsl-lite-v0-cpp17.t (Failed)
	  5 - gsl-lite-v0-cpp20.t (Failed)
	  6 - gsl-lite-v1-cpp98.t (Failed)
	  7 - gsl-lite-v1-cpp11.t (Failed)
	  8 - gsl-lite-v1-cpp14.t (Failed)
	  9 - gsl-lite-v1-cpp17.t (Failed)
	 10 - gsl-lite-v1-cpp20.t (Failed)
Errors while running CTest

```

This is gsl-lite 0.38.0. GCC versions 10.2.1 and 11.0.1. 

The complete build log is here:

- [gsl-lite-gcc-11.0.1-fedora35-s390x-buildlog.txt](https://github.com/gsl-lite/gsl-lite/files/6334524/gsl-lite-gcc-11.0.1-fedora35-s390x-buildlog.txt)
-  [gsl-lite-gcc-10.2.1-fedora33-s390x-buildlog.txt](https://github.com/gsl-lite/gsl-lite/files/6334699/gsl-lite-gcc-10.2.1-fedora33-s390x-buildlog.txt)

Build tasks for all architectures:

- Fedora 35/rawhide (GCC 11.0.1): https://koji.fedoraproject.org/koji/taskinfo?taskID=66241363 
- Fedora 34 (GCC 11.0.1): https://koji.fedoraproject.org/koji/taskinfo?taskID=66242324
- Fedora 33 (GCC 10.2.1): https://koji.fedoraproject.org/koji/taskinfo?taskID=66242329

**Comment by mbeutel** [comment] 2021-04-19 09:44
Thank you for reporting.

This sounds like a `signed`/`unsigned` issue; `char` is `unsigned` on S390x but `signed` on most other platforms. If so, we should be able to reproduce the problem on x64 by using GCC's `-funsigned-char` flag (cf. https://trofi.github.io/posts/203-signed-char-or-unsigned-char.html).

**Comment by mbeutel** [comment] 2021-04-21 23:59
Turns out this is not a `signed`/`unsigned` issue, it's related to endianness:

```c++
// test/span.t.cpp, l. 1687ff
CASE( "byte_span(): Allows to build a span of gsl::byte from a single object" )
{
    int x = (std::numeric_limits<int>::max)();

    span<gsl::byte> spn = byte_span( x );

    EXPECT( spn.size() == index_type( sizeof x ) );
    EXPECT( spn[0]     == to_byte( 0xff ) );  // this assumes a little-endian representation of `x` (and also `sizeof(int) > 1`)
}
```

S390x is big-endian, whereas all the other architectures in the list you gave at https://github.com/gsl-lite/gsl-lite/issues/303#issuecomment-822305648 are little-endian (AArch64 is bi-endian but defaults to little-endian).

Perhaps I should take this opportunity to add a [`std::endian()`](https://en.cppreference.com/w/cpp/types/endian) polyfill to *gsl-lite* ([see also](https://sourceforge.net/p/predef/wiki/Endianness/)).

**Comment by mbeutel** [comment] 2021-04-22 11:34
Sorry, didn't mean to close already.

**Comment by mbeutel** [comment] 2021-04-22 11:54
@sanjayankur31, could you please re-run tests on S390x (or, ideally, on all of your supported platforms) to see if this issue is now fixed?

**Comment by sanjayankur31** [comment] 2021-04-22 12:07
Sure. I'll build https://github.com/gsl-lite/gsl-lite/commit/6687cc1c23b948b0943259e54ac1fc55e5cd961d and get back to you before the end of the day. Thanks for the quick fix :)

**Comment by sanjayankur31** [comment] 2021-04-22 12:45
Happy to report that all tests pass on all supported arches now:

**Comment by mbeutel** [comment] 2021-04-22 12:47
Excellent, thank you. I'll prepare the 0.38.1 bugfix release in a moment.

**Closed by mbeutel** 2021-04-22 12:47 UTC
